import { Observable } from 'rxjs';
import { KioFolderSettings, KioFolderSettingArg, KioFileFilter } from '../../env';
import { IndexTypes } from '../interfaces';
export declare const resolveRootByIndexType: (indexType: IndexTypes) => KioFolderSettings;
export declare const filepathFilter: (filter: string | RegExp | KioFileFilter[]) => any;
export declare const list: (sourcePath: KioFolderSettingArg) => Observable<string>;
export declare const kioFiles: (kioPathType: string) => Observable<string>;
export declare const publicationComponents: () => Observable<string>;
export declare const structureComponents: () => Observable<string>;
export declare const navigationComponents: () => Observable<string>;
export declare const publicationComponentFiles: () => Observable<string[]>;
export declare const publicationComponentFixtures: () => Observable<string>;
export declare const publicationComponentCriterias: () => Observable<string>;
export declare const filesForIndexType: (indexType: IndexTypes) => Observable<string>;
